version: '3.2'

services:
  &app-service app:
    # https://github.com/alecrabbit/docker-php73-cli-alpine-debug
    image: dralec/php73-cli-alpine-debug
    hostname: *app-service
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}" # Set variables in .env file
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./:/var/www
    environment:
      DOCKER_TERM: "${TERM:-}"      # pass host $TERM variable
      COLORTERM: "${COLORTERM:-}"   # pass host $COLORTERM variable
    command: tail -f /dev/null
#    command: keep-alive.sh  # faster container restart
